In [4]:
# Import necessary libraries
import pandas as pd
# Import the Path class from the pathlib module to work with file paths
from pathlib import Path
# Print current working directory to verify the location of the script
print(Path.cwd().parent)

c:\Users\biswa\Downloads\AtliQ Technologies Virtual Internship -2\Netflix_india_input_file

In [5]:
# Load the dataset from a CSV file into a pandas DataFrame
input_file_path = Path.cwd().parent / "raw files" / "netflix_india_yt_data.csv"
netflix_india_yt_data_df = pd.read_csv(input_file_path)
# Print the first 5 rows of the DataFrame to get an overview of the data
netflix_india_yt_data_df.head(5)

,video_id,title,description,tags,publishedAt,thumbnails,liveBroadcastContent,viewCount,likeCount,commentCount,duration
0,KQ2a4uawQBo,Meet THE REAL Honey Singh | Yo Yo Honey Singh:...,Honey Singh shares his battles with mental hea...,"['angreji beat', 'dope shope', 'honey singh', ...",2024-12-20T08:00:00Z,{'default': {'url': 'https://i.ytimg.com/vi/KQ...,none,52864,7111.0,394.0,PT1M11S
1,bOR7S0j_wq8,⁠Akshay Kumar ALMOST Gets Caught Cheating! 👀 f...,Brb taking notes on how to lie like a pro 👀\r\...,"['aditya seal', 'akshay kumar', 'akshay kumar ...",2024-12-19T12:30:00Z,{'default': {'url': 'https://i.ytimg.com/vi/bO...,none,44300,642.0,30.0,PT3M2S
2,GRM8Q-1fVJ0,Black Warrant | Official Teaser | Vikramaditya...,"India ki sabse khatarnaak jail mein, ek naya j...","['netflix india', 'netflix', 'netflix shows', ...",2024-12-19T05:30:10Z,{'default': {'url': 'https://i.ytimg.com/vi/GR...,none,201087,3300.0,101.0,PT1M15S
3,b0b8WBglCHo,The Electric State | Official Trailer | Netfli...,"In the aftermath of the robot war, the only pa...","['AGBO', 'Action', 'Adventure', 'Anthony Russo...",2024-12-18T14:30:00Z,{'default': {'url': 'https://i.ytimg.com/vi/b0...,none,19642,354.0,25.0,PT1M44S
4,QCPOl_7cdnQ,The Electric State | Official Trailer | Hindi ...,"In the aftermath of the robot war, the only pa...","['AGBO', 'Netflix', 'Netflix पर क्या देखना चाह...",2024-12-18T13:30:05Z,{'default': {'url': 'https://i.ytimg.com/vi/QC...,none,117292,3455.0,130.0,PT1M41S

In [6]:
# Check for missing values in the DataFrame and memory usage of the DataFrame
netflix_india_yt_data_df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5198 entries, 0 to 5197
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   video_id              5198 non-null   object
 1   title                 5198 non-null   object
 2   description           5191 non-null   object
 3   tags                  5177 non-null   object
 4   publishedAt           5198 non-null   object
 5   thumbnails            5198 non-null   object
 6   liveBroadcastContent  5198 non-null   object
 7   viewCount             5198 non-null   int64
 8   likeCount             5197 non-null   float64
 9   commentCount          5191 non-null   float64
 10  duration              5198 non-null   object
dtypes: float64(2), int64(1), object(8)
memory usage: 16.0 MB

In [7]:
# check the unique values in the 'liveBroadcastContent' column to understand the different types of content available
netflix_india_yt_data_df['liveBroadcastContent'].value_counts()

liveBroadcastContent
none        5197
upcoming       1
Name: count, dtype: int64

In [8]:
# Remove unnecessary columns from the DataFrame to clean the data
netflix_india_yt_data_df.drop(columns = ['liveBroadcastContent' , 'thumbnails'] , inplace = True)

In [9]:
# Check the column names of the DataFrame to verify the changes made
netflix_india_yt_data_df.columns

Index(['video_id', 'title', 'description', 'tags', 'publishedAt', 'viewCount',
       'likeCount', 'commentCount', 'duration'],
      dtype='object')

In [10]:
# View publishedAt Column values format 
netflix_india_yt_data_df['publishedAt']

0       2024-12-20T08:00:00Z
1       2024-12-19T12:30:00Z
2       2024-12-19T05:30:10Z
3       2024-12-18T14:30:00Z
4       2024-12-18T13:30:05Z
                ...
5193    2016-07-08T05:50:54Z
5194    2016-06-17T08:08:13Z
5195    2016-06-15T07:07:53Z
5196    2016-06-13T08:12:05Z
5197    2016-05-17T06:22:50Z
Name: publishedAt, Length: 5198, dtype: object

In [11]:
# convert the 'publishedAt' column to datetime format, handling any errors by coercing them to NaT (Not a Time), and then extracting only the date part
netflix_india_yt_data_df['publishedAt'] = pd.to_datetime(netflix_india_yt_data_df['publishedAt'], errors='coerce').dt.date
# Again convert that date part into proper datetime format to ensure consistency in the data type
netflix_india_yt_data_df['publishedAt'] = pd.to_datetime(netflix_india_yt_data_df['publishedAt'])

In [12]:
# Now check the 'publishedAt' column again to confirm that the conversion was successful 
# and that the values are now in proper datetime format
netflix_india_yt_data_df.publishedAt

0      2024-12-20
1      2024-12-19
2      2024-12-19
3      2024-12-18
4      2024-12-18
          ...
5193   2016-07-08
5194   2016-06-17
5195   2016-06-15
5196   2016-06-13
5197   2016-05-17
Name: publishedAt, Length: 5198, dtype: datetime64[ns]

In [13]:
# Check for missing values in the DataFrame and memory usage of the DataFrame after cleaning
netflix_india_yt_data_df.info(memory_usage ='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5198 entries, 0 to 5197
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   video_id      5198 non-null   object
 1   title         5198 non-null   object
 2   description   5191 non-null   object
 3   tags          5177 non-null   object
 4   publishedAt   5198 non-null   datetime64[ns]
 5   viewCount     5198 non-null   int64
 6   likeCount     5197 non-null   float64
 7   commentCount  5191 non-null   float64
 8   duration      5198 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 12.6 MB

## Feature Engineering
1). Create a new column called 'tags_count' that counts the number of tags associated with each video. This can be done by counting total number of items in the tags column which is a list.

2). Create a another column called 'tags_clean'by Removing duplicates and clean the tags by stripping whitespace and converting to lowercase

In [14]:
import ast
import pandas as pd

def to_list_safe(x):
    if pd.isna(x):
        return []
    try:
        return ast.literal_eval(x)
    except (ValueError, SyntaxError):
        return []

def clean_tags(tag_list):
    return list(set(tag.strip().lower() for tag in tag_list))
# Convert the 'tags' column from string representation of lists to actual lists, handling any errors safely
netflix_india_yt_data_df['tags'] = netflix_india_yt_data_df['tags'].apply(to_list_safe)
# Remove duplicates and clean the tags by stripping whitespace and converting to lowercase
netflix_india_yt_data_df['tags_clean'] = netflix_india_yt_data_df['tags'].apply(clean_tags)
# Create a new column 'tagscount' that contains the count of tags for each row by applying the len function to the 'tags_clean' column
netflix_india_yt_data_df['tagscount'] = netflix_india_yt_data_df['tags_clean'].apply(len)

In [15]:
# Again check the first 5 rows of the DataFrame to verify the changes made
netflix_india_yt_data_df.head(5)

,video_id,title,description,tags,publishedAt,viewCount,likeCount,commentCount,duration,tags_clean,tagscount
0,KQ2a4uawQBo,Meet THE REAL Honey Singh | Yo Yo Honey Singh:...,Honey Singh shares his battles with mental hea...,"[angreji beat, dope shope, honey singh, honey ...",2024-12-20,52864,7111.0,394.0,PT1M11S,"[dope shope, yo yo honey singh glory, yo yo ho...",19
1,bOR7S0j_wq8,⁠Akshay Kumar ALMOST Gets Caught Cheating! 👀 f...,Brb taking notes on how to lie like a pro 👀\r\...,"[aditya seal, akshay kumar, akshay kumar movie...",2024-12-19,44300,642.0,30.0,PT3M2S,"[taapsee pannu, khel khel mein akshay kumar, n...",23
2,GRM8Q-1fVJ0,Black Warrant | Official Teaser | Vikramaditya...,"India ki sabse khatarnaak jail mein, ek naya j...","[netflix india, netflix, netflix shows, sacred...",2024-12-19,201087,3300.0,101.0,PT1M15S,"[non fictional series, jailer, rahul bhat, tru...",30
3,b0b8WBglCHo,The Electric State | Official Trailer | Netfli...,"In the aftermath of the robot war, the only pa...","[AGBO, Action, Adventure, Anthony Russo, Aveng...",2024-12-18,19642,354.0,25.0,PT1M44S,"[new movies, sci-fi, blockbuster, marvel, stra...",20
4,QCPOl_7cdnQ,The Electric State | Official Trailer | Hindi ...,"In the aftermath of the robot war, the only pa...","[AGBO, Netflix, Netflix पर क्या देखना चाहिए, N...",2024-12-18,117292,3455.0,130.0,PT1M41S,"[मार्वल, अड्वेंचर, फिल्मों के ट्रेलर, क्रिस प्...",20

In [16]:
'''
Convert the 'duration' column to a timedelta format, 
handling any errors by coercing them to NaT (Not a Time) to ensure that the duration 
values are in a consistent and usable format for further analysis
''' 
netflix_india_yt_data_df['duration'] = pd.to_timedelta(netflix_india_yt_data_df['duration'] , errors='coerce')

In [17]:
# Extract the total duration in minutes from the 'duration' 
# column and create a new column 'duration_minutes' to store these values, 
# rounding them to 2 decimal places for better readability and easy to analyze
netflix_india_yt_data_df['duration_minutes'] =round(netflix_india_yt_data_df['duration'].dt.total_seconds() / 60  , 2)

In [18]:
netflix_india_yt_data_df.head(5)

,video_id,title,description,tags,publishedAt,viewCount,likeCount,commentCount,duration,tags_clean,tagscount,duration_minutes
0,KQ2a4uawQBo,Meet THE REAL Honey Singh | Yo Yo Honey Singh:...,Honey Singh shares his battles with mental hea...,"[angreji beat, dope shope, honey singh, honey ...",2024-12-20,52864,7111.0,394.0,0 days 00:01:11,"[dope shope, yo yo honey singh glory, yo yo ho...",19,1.18
1,bOR7S0j_wq8,⁠Akshay Kumar ALMOST Gets Caught Cheating! 👀 f...,Brb taking notes on how to lie like a pro 👀\r\...,"[aditya seal, akshay kumar, akshay kumar movie...",2024-12-19,44300,642.0,30.0,0 days 00:03:02,"[taapsee pannu, khel khel mein akshay kumar, n...",23,3.03
2,GRM8Q-1fVJ0,Black Warrant | Official Teaser | Vikramaditya...,"India ki sabse khatarnaak jail mein, ek naya j...","[netflix india, netflix, netflix shows, sacred...",2024-12-19,201087,3300.0,101.0,0 days 00:01:15,"[non fictional series, jailer, rahul bhat, tru...",30,1.25
3,b0b8WBglCHo,The Electric State | Official Trailer | Netfli...,"In the aftermath of the robot war, the only pa...","[AGBO, Action, Adventure, Anthony Russo, Aveng...",2024-12-18,19642,354.0,25.0,0 days 00:01:44,"[new movies, sci-fi, blockbuster, marvel, stra...",20,1.73
4,QCPOl_7cdnQ,The Electric State | Official Trailer | Hindi ...,"In the aftermath of the robot war, the only pa...","[AGBO, Netflix, Netflix पर क्या देखना चाहिए, N...",2024-12-18,117292,3455.0,130.0,0 days 00:01:41,"[मार्वल, अड्वेंचर, फिल्मों के ट्रेलर, क्रिस प्...",20,1.68

In [19]:
netflix_india_yt_data_df['duration_minutes'].value_counts()

duration_minutes
0.50     56
1.68     42
0.68     42
2.05     39
1.00     39
         ..
35.92     1
25.02     1
24.32     1
44.33     1
37.35     1
Name: count, Length: 915, dtype: int64

In [20]:
netflix_india_yt_data_df.head()

,video_id,title,description,tags,publishedAt,viewCount,likeCount,commentCount,duration,tags_clean,tagscount,duration_minutes
0,KQ2a4uawQBo,Meet THE REAL Honey Singh | Yo Yo Honey Singh:...,Honey Singh shares his battles with mental hea...,"[angreji beat, dope shope, honey singh, honey ...",2024-12-20,52864,7111.0,394.0,0 days 00:01:11,"[dope shope, yo yo honey singh glory, yo yo ho...",19,1.18
1,bOR7S0j_wq8,⁠Akshay Kumar ALMOST Gets Caught Cheating! 👀 f...,Brb taking notes on how to lie like a pro 👀\r\...,"[aditya seal, akshay kumar, akshay kumar movie...",2024-12-19,44300,642.0,30.0,0 days 00:03:02,"[taapsee pannu, khel khel mein akshay kumar, n...",23,3.03
2,GRM8Q-1fVJ0,Black Warrant | Official Teaser | Vikramaditya...,"India ki sabse khatarnaak jail mein, ek naya j...","[netflix india, netflix, netflix shows, sacred...",2024-12-19,201087,3300.0,101.0,0 days 00:01:15,"[non fictional series, jailer, rahul bhat, tru...",30,1.25
3,b0b8WBglCHo,The Electric State | Official Trailer | Netfli...,"In the aftermath of the robot war, the only pa...","[AGBO, Action, Adventure, Anthony Russo, Aveng...",2024-12-18,19642,354.0,25.0,0 days 00:01:44,"[new movies, sci-fi, blockbuster, marvel, stra...",20,1.73
4,QCPOl_7cdnQ,The Electric State | Official Trailer | Hindi ...,"In the aftermath of the robot war, the only pa...","[AGBO, Netflix, Netflix पर क्या देखना चाहिए, N...",2024-12-18,117292,3455.0,130.0,0 days 00:01:41,"[मार्वल, अड्वेंचर, फिल्मों के ट्रेलर, क्रिस प्...",20,1.68

In [21]:
import numpy as np

netflix_india_yt_data_df['video_length_bucket'] = np.where(
    netflix_india_yt_data_df['duration_minutes'] <= 10,
    'Short',
    'Long'
)

In [22]:
netflix_india_yt_data_df.head(5)

,video_id,title,description,tags,publishedAt,viewCount,likeCount,commentCount,duration,tags_clean,tagscount,duration_minutes,video_length_bucket
0,KQ2a4uawQBo,Meet THE REAL Honey Singh | Yo Yo Honey Singh:...,Honey Singh shares his battles with mental hea...,"[angreji beat, dope shope, honey singh, honey ...",2024-12-20,52864,7111.0,394.0,0 days 00:01:11,"[dope shope, yo yo honey singh glory, yo yo ho...",19,1.18,Short
1,bOR7S0j_wq8,⁠Akshay Kumar ALMOST Gets Caught Cheating! 👀 f...,Brb taking notes on how to lie like a pro 👀\r\...,"[aditya seal, akshay kumar, akshay kumar movie...",2024-12-19,44300,642.0,30.0,0 days 00:03:02,"[taapsee pannu, khel khel mein akshay kumar, n...",23,3.03,Short
2,GRM8Q-1fVJ0,Black Warrant | Official Teaser | Vikramaditya...,"India ki sabse khatarnaak jail mein, ek naya j...","[netflix india, netflix, netflix shows, sacred...",2024-12-19,201087,3300.0,101.0,0 days 00:01:15,"[non fictional series, jailer, rahul bhat, tru...",30,1.25,Short
3,b0b8WBglCHo,The Electric State | Official Trailer | Netfli...,"In the aftermath of the robot war, the only pa...","[AGBO, Action, Adventure, Anthony Russo, Aveng...",2024-12-18,19642,354.0,25.0,0 days 00:01:44,"[new movies, sci-fi, blockbuster, marvel, stra...",20,1.73,Short
4,QCPOl_7cdnQ,The Electric State | Official Trailer | Hindi ...,"In the aftermath of the robot war, the only pa...","[AGBO, Netflix, Netflix पर क्या देखना चाहिए, N...",2024-12-18,117292,3455.0,130.0,0 days 00:01:41,"[मार्वल, अड्वेंचर, फिल्मों के ट्रेलर, क्रिस प्...",20,1.68,Short

In [23]:
netflix_india_yt_data_df['video_length_bucket'].value_counts()

video_length_bucket
Short    4737
Long      461
Name: count, dtype: int64

In [24]:
# Reaname columns for better understanding and clarity of the data
rename_column_list = {
    'title':'video_title',
    'description':'video_description',
    'publishedAt':'published_date',
    'likeCount':'like_count',
    'viewCount':'view_count',
    'commentCount':'comment_count',
    'tags_clean':'video_tags',
    'tagscount':'tags_count',
}

netflix_india_yt_data_df.rename(columns= rename_column_list , inplace = True)

In [25]:
netflix_india_yt_data_df.head(5)

,video_id,video_title,video_description,tags,published_date,view_count,like_count,comment_count,duration,video_tags,tags_count,duration_minutes,video_length_bucket
0,KQ2a4uawQBo,Meet THE REAL Honey Singh | Yo Yo Honey Singh:...,Honey Singh shares his battles with mental hea...,"[angreji beat, dope shope, honey singh, honey ...",2024-12-20,52864,7111.0,394.0,0 days 00:01:11,"[dope shope, yo yo honey singh glory, yo yo ho...",19,1.18,Short
1,bOR7S0j_wq8,⁠Akshay Kumar ALMOST Gets Caught Cheating! 👀 f...,Brb taking notes on how to lie like a pro 👀\r\...,"[aditya seal, akshay kumar, akshay kumar movie...",2024-12-19,44300,642.0,30.0,0 days 00:03:02,"[taapsee pannu, khel khel mein akshay kumar, n...",23,3.03,Short
2,GRM8Q-1fVJ0,Black Warrant | Official Teaser | Vikramaditya...,"India ki sabse khatarnaak jail mein, ek naya j...","[netflix india, netflix, netflix shows, sacred...",2024-12-19,201087,3300.0,101.0,0 days 00:01:15,"[non fictional series, jailer, rahul bhat, tru...",30,1.25,Short
3,b0b8WBglCHo,The Electric State | Official Trailer | Netfli...,"In the aftermath of the robot war, the only pa...","[AGBO, Action, Adventure, Anthony Russo, Aveng...",2024-12-18,19642,354.0,25.0,0 days 00:01:44,"[new movies, sci-fi, blockbuster, marvel, stra...",20,1.73,Short
4,QCPOl_7cdnQ,The Electric State | Official Trailer | Hindi ...,"In the aftermath of the robot war, the only pa...","[AGBO, Netflix, Netflix पर क्या देखना चाहिए, N...",2024-12-18,117292,3455.0,130.0,0 days 00:01:41,"[मार्वल, अड्वेंचर, फिल्मों के ट्रेलर, क्रिस प्...",20,1.68,Short

In [26]:
# Check for null count in each column of the DataFrame to identify any missing values that may need to be addressed
netflix_india_yt_data_df.isnull().sum()

video_id               0
video_title            0
video_description      7
tags                   0
published_date         0
view_count             0
like_count             1
comment_count          7
duration               0
video_tags             0
tags_count             0
duration_minutes       0
video_length_bucket    0
dtype: int64

In [27]:
netflix_india_yt_data_df.head(5)

,video_id,video_title,video_description,tags,published_date,view_count,like_count,comment_count,duration,video_tags,tags_count,duration_minutes,video_length_bucket
0,KQ2a4uawQBo,Meet THE REAL Honey Singh | Yo Yo Honey Singh:...,Honey Singh shares his battles with mental hea...,"[angreji beat, dope shope, honey singh, honey ...",2024-12-20,52864,7111.0,394.0,0 days 00:01:11,"[dope shope, yo yo honey singh glory, yo yo ho...",19,1.18,Short
1,bOR7S0j_wq8,⁠Akshay Kumar ALMOST Gets Caught Cheating! 👀 f...,Brb taking notes on how to lie like a pro 👀\r\...,"[aditya seal, akshay kumar, akshay kumar movie...",2024-12-19,44300,642.0,30.0,0 days 00:03:02,"[taapsee pannu, khel khel mein akshay kumar, n...",23,3.03,Short
2,GRM8Q-1fVJ0,Black Warrant | Official Teaser | Vikramaditya...,"India ki sabse khatarnaak jail mein, ek naya j...","[netflix india, netflix, netflix shows, sacred...",2024-12-19,201087,3300.0,101.0,0 days 00:01:15,"[non fictional series, jailer, rahul bhat, tru...",30,1.25,Short
3,b0b8WBglCHo,The Electric State | Official Trailer | Netfli...,"In the aftermath of the robot war, the only pa...","[AGBO, Action, Adventure, Anthony Russo, Aveng...",2024-12-18,19642,354.0,25.0,0 days 00:01:44,"[new movies, sci-fi, blockbuster, marvel, stra...",20,1.73,Short
4,QCPOl_7cdnQ,The Electric State | Official Trailer | Hindi ...,"In the aftermath of the robot war, the only pa...","[AGBO, Netflix, Netflix पर क्या देखना चाहिए, N...",2024-12-18,117292,3455.0,130.0,0 days 00:01:41,"[मार्वल, अड्वेंचर, फिल्मों के ट्रेलर, क्रिस प्...",20,1.68,Short

In [28]:
len(netflix_india_yt_data_df)

5198

In [29]:
# Create a new column called 'title_length' that 
# calculates the length of each video title
# after cleaning it by removing any non-ASCII characters and stripping whitespace. 
# This will help in analyzing the titles more effectively.
netflix_india_yt_data_df['title_length'] = netflix_india_yt_data_df['video_title'].astype('str').str.replace(
    r"[^\x20-\x7E]",
    "",
    regex=True
).str.strip().str.len()

In [30]:
def find_video_theme(video_title):
    # Convert the title to lowercase for case-insensitive matching
    title_lower = video_title.lower()
    
    # Define keywords for different themes
    themes = {
        'Comedy': ['funny', 'comedy', 'humor', 'hilarious'],
        'Drama': ['drama', 'emotional', 'intense', 'heartfelt'],
        'Action': ['action', 'thriller', 'adventure', 'fight'],
        'Romance': ['romance', 'love', 'relationship', 'affection'],
        'Horror': ['horror', 'scary', 'frightening', 'terror'],
        'Teaser': ['teaser', 'trailer', 'preview', 'sneak peek'],
        'Clip': ['clip', 'scene', 'snippet', 'highlight'],
        'Announcement': ['announcement', 'news', 'update', 'release'],
        'Song': ['song', 'music', 'track', 'melody'],
        'Interview': ['interview', 'discussion', 'talk', 'conversation'],
        'Behind the Scenes': ['behind the scenes', 'bts', 'making of', 'production']        
        # Add more themes and keywords as needed
    }
    
    # Check for keywords in the title and return the corresponding theme
    for theme, keywords in themes.items():
        if any(keyword in title_lower for keyword in keywords):
            return theme
    
    # If no keywords match, return 'Other'
    return 'Other'

In [31]:
# Create a new column 'content_theme' in the DataFrame 
# by applying the find_video_theme function to the 'video_title' column
netflix_india_yt_data_df['content_theme'] = netflix_india_yt_data_df['video_title'].apply(find_video_theme)

In [32]:
# Create two dataframes, one with all columns and another with selected columns for further analysis or reporting
netflix_india_yt_data_df1 = netflix_india_yt_data_df[netflix_india_yt_data_df.columns.to_list()]

netflix_india_yt_data_df = netflix_india_yt_data_df[['video_id','content_theme','published_date','like_count','view_count','comment_count','tags_count','duration_minutes',	'video_length_bucket' , 'title_length']]

In [33]:
# Remove Duplicates from the dataframe to ensure that each video entry is unique, 
# keeping the first occurrence of any duplicate entries and dropping the rest
netflix_india_yt_data_df.drop_duplicates(keep = 'first' , inplace = True)

In [34]:
len(netflix_india_yt_data_df)

5198

In [35]:
netflix_india_yt_data_df.info(memory_usage = 'deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5198 entries, 0 to 5197
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   video_id             5198 non-null   object
 1   content_theme        5198 non-null   object
 2   published_date       5198 non-null   datetime64[ns]
 3   like_count           5197 non-null   float64
 4   view_count           5198 non-null   int64
 5   comment_count        5191 non-null   float64
 6   tags_count           5198 non-null   int64
 7   duration_minutes     5198 non-null   float64
 8   video_length_bucket  5198 non-null   object
 9   title_length         5198 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(3), object(3)
memory usage: 1.2 MB

In [36]:
# Remove rows where view_count is 0, 
# view_count is less than like_count or comment_count, and duration_minutes is 0
netflix_india_yt_data_df = netflix_india_yt_data_df[
      (netflix_india_yt_data_df['view_count'] != 0) 
    & (netflix_india_yt_data_df['view_count'] >= netflix_india_yt_data_df['like_count']) 
    & (netflix_india_yt_data_df['view_count'] >= netflix_india_yt_data_df['comment_count'])
    & (netflix_india_yt_data_df['duration_minutes'] != 0 )
]

In [37]:
len(netflix_india_yt_data_df)

5189

In [38]:
# Check for rows where duration_minutes is 0 to identify any remaining anomalies in the data
netflix_india_yt_data_df[(netflix_india_yt_data_df['duration_minutes'] == 0 )]

Empty DataFrame
Columns: [video_id, content_theme, published_date, like_count, view_count, comment_count, tags_count, duration_minutes, video_length_bucket, title_length]
Index: []

In [39]:
# Remove invalid video_id entries that contain the string "#NAME?" to ensure data integrity
netflix_india_yt_data_df = netflix_india_yt_data_df[(netflix_india_yt_data_df['video_id'] != "#NAME?")]

In [40]:
len(netflix_india_yt_data_df)

5124

In [41]:
netflix_india_yt_data_df['video_id'].drop_duplicates().count()

5124

In [42]:
netflix_india_yt_data_df['weekday'] = netflix_india_yt_data_df['published_date'].dt.day_name()

netflix_india_yt_data_df['comment_rate'] =round(netflix_india_yt_data_df['comment_count'] * 100 / netflix_india_yt_data_df['view_count'] , 2)

netflix_india_yt_data_df['like_rate'] = round(netflix_india_yt_data_df['like_count'] * 100 / netflix_india_yt_data_df['view_count'] , 2)

In [43]:
netflix_india_yt_data_df['video_id'].drop_duplicates().count()

5124

In [44]:
# Save the cleaned and processed DataFrame to a new CSV file 
# in a designated output folder for further analysis or reporting
from pathlib import Path

output_folder = Path.cwd().parent / "processed files"

output_folder.mkdir(exist_ok=True)

netflix_india_yt_data_df.to_csv(
    output_folder / "netflix_india_yt_data.csv",
    index=False
)

In [45]:
netflix_india_yt_data_df1 = netflix_india_yt_data_df1[
      (netflix_india_yt_data_df1['view_count'] != 0) 
    & (netflix_india_yt_data_df1['view_count'] >= netflix_india_yt_data_df1['like_count']) 
    & (netflix_india_yt_data_df1['view_count'] >= netflix_india_yt_data_df1['comment_count'])
    & (netflix_india_yt_data_df1['duration_minutes'] != 0 )
]

In [46]:
len(netflix_india_yt_data_df1)

5189

In [47]:
netflix_india_yt_data_df1 = netflix_india_yt_data_df1[(netflix_india_yt_data_df1['video_id'] != "#NAME?")]

In [48]:
len(netflix_india_yt_data_df1)

5124

In [49]:
# Create another dataframe by exploding the 'video_tags' column to have one tag per row, while keeping the 'video_id' for reference. 
# This will help in analyzing the tags more effectively.
video_tags_df = netflix_india_yt_data_df1.explode(column = 'video_tags')[['video_id' , 'video_tags']]

In [50]:
# Check the len of the video_tags_df dataframe length before deleteing duplicates
len(video_tags_df)

93915

In [51]:
# Remove duplicate rows from the video_tags_df DataFrame to ensure that each video_id and tag combination is unique
video_tags_df.drop_duplicates(inplace = True)

In [52]:
len(video_tags_df)

93915

In [53]:
# Save the cleaned and processed video_tags_df DataFrame to a new CSV file
from pathlib import Path

output_folder = Path.cwd().parent / "processed files"
output_folder.mkdir(exist_ok=True)

video_tags_df.to_csv(
    output_folder / "video_tags_list.csv",
    index=False
)

In [54]:
new_df = netflix_india_yt_data_df1[['video_id', 'video_title']]

new_df['video_title'] = new_df['video_title'].astype('str').str.replace(
    r"[^\x20-\x7E]",
    "",
    regex=True
).str.split("|")

video_title_df = new_df.explode(column= 'video_title')[['video_id' , 'video_title']]

video_title_df['video_title'] = video_title_df['video_title'].astype('str').str.strip().str.title().str.replace("  " , " ")

video_title_df.rename(columns = {'video_title':'title_list'} , inplace = True)

video_title_df.head(5)

C:\Users\biswa\AppData\Local\Temp\ipykernel_8048\1661039304.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['video_title'] = new_df['video_title'].astype('str').str.replace(

      video_id                                         title_list
0  KQ2a4uawQBo                          Meet The Real Honey Singh
0  KQ2a4uawQBo                          Yo Yo Honey Singh: Famous
0  KQ2a4uawQBo                                          Watch Now
0  KQ2a4uawQBo                                      Netflix India
1  bOR7S0j_wq8  Akshay Kumar Almost Gets Caught Cheating! Ft T...

In [55]:
len(video_title_df)

14570

In [56]:
video_title_df.drop_duplicates(keep = 'first' , inplace = True)

In [57]:
len(video_title_df)

14564

In [58]:
# Save the cleaned and processed video_title_df DataFrame to a new CSV file
from pathlib import Path

output_folder = Path.cwd().parent / "processed files"
output_folder.mkdir(exist_ok=True)

video_title_df.to_csv(
    output_folder / "video_title_keyword.csv",
    index=False
)